{% render "xpacks/xpack-dev-tools-xbb-helper/templates/copyright-liquid.yml" %}

{% if platforms == "all" -%}
  {% assign platforms = "linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64,win32-x64" -%}
{% endif -%}
{% assign platforms = platforms | split: "," -%}

name: 'Build xPack {{ XBB_APPLICATION_NAME }} xbbli'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semver of the release'
        required: false
        default: 'current'

jobs:
{% for platform in platforms -%}
  {% if platform == "linux-x64" or platform == "win32-x64" or platform == "linux-ia32" or platform == "win32-ia32" %}
  linux-x64:
    name: 'Linux Intel - {{ XBB_APPLICATION_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} build'
    timeout-minutes: 5760 # 4 days
    runs-on: [self-hosted, linux, x64]
    container:
      image: ilegeul/ubuntu:amd64-18.04-xbb-v4.0
    defaults:
      run:
        shell: bash --login -e -o pipefail {0} # For node PATH

    steps:
      - name: 'Environment'
        run: |
          uname -a
          lsb_release -sd
          whoami
          pwd
          node --version
          npm --version
          ls -lLA
          env

      - name: 'Clean working area'
        run: rm -rf * .git*

      - name: 'Checkout project'
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: 'Install xpm'
        timeout-minutes: 1440
        run: npm install --global xpm@latest

      - name: 'Install project dependencies'
        timeout-minutes: 1440
        run: xpm install
{% for platform in platforms -%}
  {% case platform -%}
    {% when "linux-x64" %}
      - name: 'Build Linux x64 binary'
        timeout-minutes: 1440
        run: |
          xpm install --config linux-x64
          xpm run build --config linux-x64
    {% when "win32-x64" %}
      - name: 'Build Windows x64 binary'
        timeout-minutes: 1440
        run: |
          xpm install --config win32-x64
          xpm run build --config win32-x64
  {% endcase -%}
{% endfor %}
      - name: 'Publish pre-release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'build/linux-x64/deploy/*,build/win32-x64/deploy/*'
          bodyFile: '.github/workflows/body-github-pre-releases-test.md'
          commit: 'master'
          draft: false
          name: 'Test binaries'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: 'pre-releases'
          tag: 'test'
          token: {% raw %}${{ secrets.PUBLISH_TOKEN }}{% endraw %}

      - name: 'Rename working area'
        # For just in case absolute paths remain unprocessed.
        run: mv -v build build-$(date -u +%Y%m%d-%H%M%S)
{% break -%}
{% endif -%}
{% endfor -%}
