{% render "xpacks/xpack-dev-tools-xbb-helper/templates/copyright-liquid.yml" %}

{% if platforms == "all" -%}
  {% assign platforms = "linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64,win32-x64" -%}
{% endif -%}
{% assign platforms = platforms | split: "," -%}

name: 'Build xPack {{ XBB_APPLICATION_NAME }} xbbmi'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semver of the release'
        required: false
        default: 'current'

jobs:
{% for platform in platforms -%}
{% if platform == "darwin-x64" %}
  macos-x64:
    name: 'macOS Intel - {{ XBB_APPLICATION_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} build'
    timeout-minutes: 2880 # 2 days
{% if MACOS_INTEL_VERSION %}
    runs-on: [self-hosted, macos, intel, {{ MACOS_INTEL_VERSION }}]
{% else %}
    runs-on: [self-hosted, macos, intel]
{% endif %}
    steps:
      - name: 'Environment'
        run: |
          uname -a
          sw_vers
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          echo "node: $(node --version)"
          echo "npm: $(npm --version)"
          ls -lLA
          env | sort | egrep '^[^\s][^\s]*='

      - name: 'Clean working area'
        run: rm -rf * .git*

      - name: 'Checkout project'
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: 'Install xpm'
        timeout-minutes: 1440
        run: npm install --location=global xpm@latest

      - name: 'Install project dependencies'
        timeout-minutes: 1440
        run: xpm install
{% for platform in platforms -%}
  {% case platform -%}
    {% when "darwin-x64" %}
      - name: 'Build macOS x64 binary'
        timeout-minutes: 1440
        run: |
          xpm install --config darwin-x64
          xpm run build --config darwin-x64
  {% endcase -%}
{% endfor %}
      - name: 'Publish pre-release'
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: 'build/darwin-x64/deploy/*'
          bodyFile: '.github/workflows/body-github-pre-releases-test.md'
          commit: 'master'
          draft: false
          name: 'Test binaries'
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          owner: 'xpack-dev-tools'
          prerelease: true
          replacesArtifacts: true
          repo: 'pre-releases'
          tag: 'test'
          token: {% raw %}${{ secrets.PUBLISH_TOKEN }}{% endraw %}

      - name: 'Rename working area'
        # For just in case absolute paths remain unprocessed.
        run: mv -v build build-$(date -u +%Y%m%d-%H%M%S)
{% break -%}
{% endif -%}
{% endfor -%}
