{% render "xpacks/@xpack-dev-tools/xbb-helper/templates/copyright-liquid.yml" %}

{% if platforms == "all" -%}
  {% assign platforms = "linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64,win32-x64" -%}
{% endif -%}
{% assign platforms = platforms | split: "," -%}

name: 'Deep clean xPack {{ XBB_APPLICATION_NAME }}'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semver of the release'
        required: false
        default: 'current'

jobs:
{% for platform in platforms -%}
{% if platform == "linux-x64" or platform == "win32-x64" %}
  linux-x64:
    name: 'Linux Intel - {{ XBB_APPLICATION_LOWER_CASE_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} clean'
    timeout-minutes: 5760 # 4 days
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: 'Environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | egrep '^[^ \t]+='

      - name: 'Clean working area'
        run: rm -rf * .git*
{% break -%}
{% endif -%}
{% endfor %}

{% for platform in platforms -%}
{% if platform == "linux-arm" %}
  linux-arm:
    name: 'Linux Arm 32 - {{ XBB_APPLICATION_LOWER_CASE_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} clean'
    timeout-minutes: 2880 # 2 days
    runs-on: [self-hosted, linux, arm, xbbla32]

    steps:
      - name: 'Environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | egrep '^[^ \t]+='

      - name: 'Clean working area'
        run: rm -rf * .git*
{% break -%}
{% endif -%}
{% endfor %}

{% for platform in platforms -%}
{% if platform == "linux-arm64" %}
  linux-arm64:
    name: 'Linux Arm 64 - {{ XBB_APPLICATION_LOWER_CASE_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} clean'
    timeout-minutes: 2880 # 2 days
    runs-on: [self-hosted, linux, arm64, xbbla]
    steps:
      - name: 'Environment'
        run: |
          uname -a
          lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | egrep '^[^ \t]+='

      - name: 'Clean working area'
        run: rm -rf * .git*
{% break -%}
{% endif -%}
{% endfor %}

{% for platform in platforms -%}
{% if platform == "darwin-x64" %}
  macos-x64:
    name: 'macOS Intel - {{ XBB_APPLICATION_LOWER_CASE_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} clean'
    timeout-minutes: 2880 # 2 days
{% if MACOS_INTEL_VERSION %}
    runs-on: [self-hosted, macos, intel, {{ MACOS_INTEL_VERSION }}]
{% else %}
    runs-on: [self-hosted, macos, intel]
{% endif %}
    steps:
      - name: 'Environment'
        run: |
          uname -a
          sw_vers # lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | egrep '^[^ \t]+='

      - name: 'Clean working area'
        run: rm -rf * .git*
{% break -%}
{% endif -%}
{% endfor %}

{% for platform in platforms -%}
{% if platform == "darwin-arm64" %}
  macos-arm64:
    name: 'macOS Arm - {{ XBB_APPLICATION_LOWER_CASE_NAME }} {% raw %}${{ github.event.inputs.version }}{% endraw %} clean'
    timeout-minutes: 2880 # 2 days
{% if MACOS_ARM_VERSION %}
    runs-on: [self-hosted, macos, apple, {{ MACOS_ARM_VERSION }}]
{% else %}
    runs-on: [self-hosted, macos, apple]
{% endif %}
    steps:
      - name: 'Environment'
        run: |
          uname -a
          sw_vers # lsb_release -sd
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          ls -lLA
          env | sort | egrep '^[^ \t]+='

      - name: 'Clean working area'
        run: rm -rf * .git*
{% break -%}
{% endif -%}
{% endfor -%}
